/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package mx.tecnm.cdmadero.almacen.gui;

import java.sql.Connection;
import javax.swing.JDialog;
import mx.tecnm.cdmadero.almacen.model.Producto;
import mx.tecnm.cdmadero.almacen.model.TablaInventario;

/**
 *
 * @author Fernando Manzanares
 */
public class FrameInventario extends javax.swing.JInternalFrame {

    FrameAlmacen framePrincipal;
    Connection conexion;

    public void setFramePrincipal(FrameAlmacen framePrincipal) {
        this.framePrincipal = framePrincipal;
    }
    /**
     * Creates new form FrameInventario
     */
    private FrameInventario(TablaInventario inventario, Connection conexion) {
        initComponents();
        this.inventario = inventario;
        this.conexion = conexion;
        initTable();
        this.tblInventario.setBounds(0, 0, 600, 500);
        this.setVisible(true);   
    }
    
    static private FrameInventario instance = null;
    static public FrameInventario getInstance(TablaInventario inventario, Connection conexion){
        if (instance == null){
            instance = new FrameInventario(inventario, conexion);
            
        }
        return instance;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();
        btnNuevoProducto = new javax.swing.JButton();
        btnAgregarProducto = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblInventario.setMinimumSize(new java.awt.Dimension(150, 150));
        tblInventario.setPreferredSize(new java.awt.Dimension(150, 150));
        jScrollPane1.setViewportView(tblInventario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 410, 300));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        btnNuevoProducto.setText("Nuevo producto");
        getContentPane().add(btnNuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        setBounds(0, 0, 591, 496);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        //this.inventario.getProductos().add(new Producto());
        //Integer numeroDeNuevaFila = this.inventario.getProductos().size() - 1;
        //this.inventario.fireTableRowsInserted( numeroDeNuevaFila, numeroDeNuevaFila);
        DialogProducto dialog = new DialogProducto(this.framePrincipal, true, );
        
        dialog.setVisible(true);
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInventario;
    // End of variables declaration//GEN-END:variables

    private TablaInventario inventario;
    static private FrameInventario frameInventario = null;
    private String[][] productos;
     
    private void initTable() {
        this.tblInventario.setModel(this.inventario);
    }
}
