/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package mx.tecnm.cdmadero.almacen.gui;

import java.sql.Connection;
import java.util.List;
import mx.tecnm.cdmadero.almacen.model.TablaInventario;

/**
 *
 * @author Fernando Manzanares
 */
public class FrameMovimiento extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameMovimiento
     */
    private  FrameMovimiento(TablaInventario inventario, Connection conexion) {
        this.con = conexion;
        this.inventario = inventario;
        initComponents();
        this.setBounds(601, 0, 410, 315);
        this.initComboProductos();
    }
    
    public static FrameMovimiento getInstance(TablaInventario inventario, Connection conexion) {
        if (instance == null){
            instance = new FrameMovimiento(inventario, conexion);
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProducto = new javax.swing.JLabel();
        cmbProducto = new javax.swing.JComboBox<>();
        lblTipoDeMovimiento = new javax.swing.JLabel();
        cmbTipoDeMovimiento = new javax.swing.JComboBox<>();
        lblCantidad = new javax.swing.JLabel();
        sprCantidad = new javax.swing.JSpinner();
        btnProcesar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        lblProducto.setText("Producto:");

        lblTipoDeMovimiento.setText("Tipo:");

        cmbTipoDeMovimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Salida" }));

        lblCantidad.setText("Cantidad:");

        btnProcesar.setText("Registrar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoDeMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbTipoDeMovimiento, 0, 236, Short.MAX_VALUE))
                            .addComponent(sprCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnProcesar)
                        .addGap(32, 32, 32)
                        .addComponent(btnCerrar)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto)
                    .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoDeMovimiento)
                    .addComponent(cmbTipoDeMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(sprCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcesar)
                    .addComponent(btnCerrar))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        setBounds(0, 0, 410, 315);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        int index = this.cmbProducto.getSelectedIndex();
        
        
        if (this.cmbTipoDeMovimiento.getSelectedIndex() == 0){
            this.inventario.getProductos().get(index).setExistencia(
                    this.inventario.getProductos().get(index).getExistencia() + (Integer) (this.sprCantidad.getValue())
            );
        }else {
            this.inventario.getProductos().get(index).setExistencia(
                    this.inventario.getProductos().get(index).getExistencia() - (Integer) (this.sprCantidad.getValue())
            );
        }
        this.inventario.fireTableCellUpdated(index, 1);
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void initComboProductos(){
        String[] nombreProductos = new String[this.inventario.getProductos().size()];
        for (int i = 0; i < this.inventario.getProductos().size(); i++){
            nombreProductos[i] = this.inventario.getProductos().get(i).getNombre();
        }
        cmbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(nombreProductos));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JComboBox<String> cmbProducto;
    private javax.swing.JComboBox<String> cmbTipoDeMovimiento;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblTipoDeMovimiento;
    private javax.swing.JSpinner sprCantidad;
    // End of variables declaration//GEN-END:variables

    TablaInventario inventario;
    private static FrameMovimiento instance;
    private Connection con;
}
