/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package mx.tecnm.cdmadero.almacen.gui;

import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import mx.tecnm.cdmadero.almacen.model.Producto;
import mx.tecnm.cdmadero.almacen.model.TablaInventario;

/**
 *
 * @author Fernando Manzanares
 */
public class FrameAlmacen extends javax.swing.JFrame {

    /**
     * Creates new form FrameAlmacen
     */
    public FrameAlmacen() {
        this.inventario = new TablaInventario();
        String connectionUrl = "jdbc:sqlserver://127.0.0.1:1433;encrypt=false;databaseName=Northwind;user=northwindUser;password=12345";
        try {
            this.conexion = DriverManager.getConnection(connectionUrl);
            System.out.println("Conectado");
        } catch (Exception e) {
            System.out.println("Fallo en la conexión");
            System.out.println(e.toString());
            e.printStackTrace();
        }
        this.cargarInventario();
        initComponents();
        
        this.init();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private void init(){
        this.frameMovimiento = FrameMovimiento.getInstance(this.inventario, this.conexion);
        this.getContentPane().add(frameMovimiento);
        this.frameMovimiento.setVisible(false);
        
        this.frameInventario = FrameInventario.getInstance(this.inventario, conexion );
        this.getContentPane().add(this.frameInventario);
        this.frameInventario.setVisible(false);
        
        this.frameProducto = FrameProducto.getInstance( this.inventario);
        this.getContentPane().add(this.frameProducto);
        this.frameProducto.setVisible(false);
        
        this.frameInventario.setFramePrincipal(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        menuItemInventario = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Abrir");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Guardar");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Herramientas");

        menuItemInventario.setMnemonic('t');
        menuItemInventario.setText("Inventario");
        menuItemInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInventarioActionPerformed(evt);
            }
        });
        editMenu.add(menuItemInventario);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Movimientos");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Producto");
        pasteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(pasteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Acerca");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(702, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        try {
            conexion.close();
        } catch (Exception e) {
        }
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void menuItemInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInventarioActionPerformed
        try {
            this.frameInventario.setVisible(true);
            this.frameInventario.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrameAlmacen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemInventarioActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        try {
            this.frameMovimiento.setVisible(true);
            this.frameMovimiento.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrameAlmacen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void pasteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteMenuItemActionPerformed
         try {
            this.frameProducto.setVisible(true);
            this.frameProducto.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrameAlmacen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pasteMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
//        JSONObject jsonObject = new JSONObject();
//         Convert the ArrayList to a JSON array
//        ObjectMapper objectMapper = new ObjectMapper();
//       try {
//          String jsonArray
//                = objectMapper.writeValueAsString(this.inventario.getProductos());
//            System.out.println(jsonArray);
//            FileWriter archivo = new FileWriter("inventario.txt");
//            archivo.write(jsonArray.toString());
//            archivo.close();
//        }  catch (JsonProcessingException e) {
//            e.printStackTrace();
//        } catch (IOException ex) {
//            Logger.getLogger(FrameAlmacen.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    }//GEN-LAST:event_saveMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
        Conectarse a la base de datos
        */
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAlmacen().setVisible(true);
            }
        });
    }
    
    private void cargarInventario(){
        List<Producto> productos = new ArrayList<>();
        
        try {
            Statement stament = conexion.createStatement();
            ResultSet rs = stament.executeQuery("SELECT * FROM producto");
            while (rs.next()) {
                Producto producto = new Producto(rs.getString("nombre"), rs.getInt("existencia"));
                productos.add(producto);
            }    
        } catch (Exception e) {
        }
        
        this.inventario.setProductos(productos);
        
    //} catch (FileNotFoundException e) {
     // System.out.println("An error occurred.");
     // e.printStackTrace();
    //}   catch (JsonProcessingException ex) {
            //Logger.getLogger(FrameAlmacen.class.getName()).log(Level.SEVERE, null, ex);
        //}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemInventario;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

    private TablaInventario inventario;
    private  mx.tecnm.cdmadero.almacen.gui.FrameInventario frameInventario;
    private FrameMovimiento frameMovimiento;
    private FrameProducto frameProducto;
    private Connection conexion;
}
